// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfusideciciedpmtfune.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmdXNpZGVjaWNpZWRwbXRmdW5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDQzNzEsImV4cCI6MjA2NzIyMDM3MX0.GY1hpuiPl3Uyk7gIFQsHbt27CTtpa569ss-k5xvo35w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});